### ISSUE TITLE
Convert to protobuf database access

### ISSUE THREAD

**Issue by david-allison-1** [david-allison-1/Anki-Android-Backend#12]
We currently use JSON (Python's Protobuf was deemed to be too slow). Using protobuf should give us a speed boost here, but we'll need to profile.

https://github.com/david-allison-1/Anki-Android-Backend/blob/5b75b4c4070f39f772d1b0c72aa339d684db34f5/rslib-bridge/src/lib.rs#L133

**Comment by dae** [comment]
It's likely a decent win in Java - the Python implementation is just awful.

https://auth0.com/blog/beating-json-performance-with-protobuf/#:~:text=When%20using%20Protobuf%20on%20a,faster%20than%20the%20text%20format.&text=Protobuf%20performed%206%20times%20faster,150ms%20on%20a%20JSON%20format.

Might make the suggested file spooling option in #6 more complicated though.
